spring.application.name=sales


dev-sarinah-portal.base.url=${BASE_URL_DEV}
sarinah-portal.base-url=${BASE_URL}
sarinah-portal.loyalty.url=${sarinah-portal.base-url}/member_loyalty
sarinah-portal.pos-order-history.url=${sarinah-portal.base-url}/pos_order_history
sarinah-portal.journal-entries-coa-harmonisasi.url=${sarinah-portal.base-url}/journal_entries_coa_harmonisasi
sarinah-portal.barcode.url=${dev-sarinah-portal.base.url}/product_by_barcode

# HTTP Client settings
http.client.max-connections=300
http.client.max-per-route=100
http.client.connection-request-timeout=20000
http.client.connect-timeout=20000
http.client.read-timeout=20000

server.port=8083
server.address=0.0.0.0
security.api-key=${API_KEY}
